-- MySQL Script generated by MySQL Workbench
-- Пн 19 сен 2016 12:20:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema skyeng
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `skyeng` ;

-- -----------------------------------------------------
-- Schema skyeng
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skyeng` DEFAULT CHARACTER SET utf8 ;
USE `skyeng` ;

-- -----------------------------------------------------
-- Table `skyeng`.`word_eng`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skyeng`.`word_eng` ;

CREATE TABLE IF NOT EXISTS `skyeng`.`word_eng` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(255) BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skyeng`.`word_ru`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skyeng`.`word_ru` ;

CREATE TABLE IF NOT EXISTS `skyeng`.`word_ru` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(255) BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skyeng`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skyeng`.`relation` ;

CREATE TABLE IF NOT EXISTS `skyeng`.`relation` (
  `ru` INT NOT NULL,
  `eng` INT NOT NULL,
  PRIMARY KEY (`ru`, `eng`),
  INDEX `fk_relation_2_idx` (`eng` ASC),
  CONSTRAINT `fk_relation_1`
    FOREIGN KEY (`ru`)
    REFERENCES `skyeng`.`word_ru` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_relation_2`
    FOREIGN KEY (`eng`)
    REFERENCES `skyeng`.`word_eng` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skyeng`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skyeng`.`test` ;

CREATE TABLE IF NOT EXISTS `skyeng`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `evaluation` INT(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skyeng`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skyeng`.`errors` ;

CREATE TABLE IF NOT EXISTS `skyeng`.`errors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_id` INT NOT NULL,
  `data` JSON NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_errors_1_idx` (`test_id` ASC),
  CONSTRAINT `fk_errors_1`
    FOREIGN KEY (`test_id`)
    REFERENCES `skyeng`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
